// File generated by FlutterFire CLI.
// Not: Bu dosyanın gerçek uygulamanızda FlutterFire CLI tarafından oluşturulması gerekir.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Bu sınıf, Firebase yapılandırma seçeneklerini sağlar.
/// Gerçek uygulamanızda bu dosya FlutterFire CLI tarafından oluşturulmalıdır.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Web için varsayılan Firebase yapılandırması
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Varsayılan FirebaseOptions, Linux platformu için yapılandırılmamış.',
        );
      default:
        throw UnsupportedError(
          'Varsayılan FirebaseOptions, $defaultTargetPlatform platformu için yapılandırılmamış.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnrRpkiERKF1iLYEbhyeHPLC4wT1b6LSc',
    appId: '1:96024549878:web:456ff90010af8f70fa4fd7',
    messagingSenderId: '96024549878',
    projectId: 'bitirme3-835df',
    authDomain: 'bitirme3-835df.firebaseapp.com',
    storageBucket: 'bitirme3-835df.appspot.com',
  );

  // Bu yapılandırma seçeneklerini kendi Firebase projenizdeki seçeneklerle değiştirin

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs3KmcmQCsEq_OtLoaylyp6vZNehIRz_U',
    appId: '1:96024549878:android:cd2a3333f1dafbfffa4fd7',
    messagingSenderId: '96024549878',
    projectId: 'bitirme3-835df',
    storageBucket: 'bitirme3-835df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASUiuob3z2j1uY9xc3cI6YXdmFJX3HzEY',
    appId: '1:96024549878:ios:d4f734161d172095fa4fd7',
    messagingSenderId: '96024549878',
    projectId: 'bitirme3-835df',
    storageBucket: 'bitirme3-835df.appspot.com',
    iosBundleId: 'com.example.bitirme3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASUiuob3z2j1uY9xc3cI6YXdmFJX3HzEY',
    appId: '1:96024549878:ios:d4f734161d172095fa4fd7',
    messagingSenderId: '96024549878',
    projectId: 'bitirme3-835df',
    storageBucket: 'bitirme3-835df.appspot.com',
    iosBundleId: 'com.example.bitirme3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnrRpkiERKF1iLYEbhyeHPLC4wT1b6LSc',
    appId: '1:96024549878:web:cabf9625e4437be4fa4fd7',
    messagingSenderId: '96024549878',
    projectId: 'bitirme3-835df',
    authDomain: 'bitirme3-835df.firebaseapp.com',
    storageBucket: 'bitirme3-835df.appspot.com',
  );
}
